# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.\output' 
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/UDAntd.zip' 

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'UDAntd'
    targetPath: $(Build.ArtifactStagingDirectory)


- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'alongviliud - Azure'
    Action: 'Stop Azure App Service'
    WebAppName: 'alongviliud'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'alongviliud - Azure'
    appType: 'webApp'
    appName: 'alongviliud'
    deployToSlotOrASE: true
    resourceGroupName: 'udd'
    slotName: 'production'
    package: '$(Build.ArtifactStagingDirectory)/UDAntd.zip'
    deploymentMethod: 'auto'